fixxes

diff --git a/tftp/distro/debian/setup b/tftp/distro/debian/setup
--- a/tftp/distro/debian/setup
+++ b/tftp/distro/debian/setup
@@ -1,7 +1,8 @@
-#!/bin/bash -x
+#!/bin/bash 
 PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
 TIMESTAMP="$(date '+%Y%m%dB')"
 MIRROR="http://nl-mirror.eurid.eu/debian"
+DIRNAME=$( pwd -P )
 
 # Functions 
 
@@ -20,25 +21,25 @@ function main() {
     for DISTRO in squeeze wheezy
     do 
         echo "Preparing for $DISTRO"
-        for ARCH in i386 amd64
-        do
+        for ARCH in "i386" "amd64"
+            do
             echo "Setting up $ARCH"
 
-            if [ ! -d "./$DISTRO/$ARCH" ] ; then 
-                mkdir -p "./$DISTRO/$ARCH" || die "Failed to create ./$DISTRO/$ARCH"
+            if [ ! -d "$DIRNAME/$DISTRO/$ARCH" ] ; then 
+                mkdir -p "$DIRNAME/$DISTRO/$ARCH" || die "Failed to create $DISTRO/$ARCH"
             fi 
         
             echo "Backing up current kernel and initrd.gz"
             for FILE in linux initrd.gz
             do
-               if [ -f "./$DISTRO/$ARCH/$FILE" ] ; then 
-                    mv "./$DISTRO/$ARCH/$FILE" "./$DISTRO/$ARCH/$FILE.$TIMESTAMP"
+               if [ -f "$DIRNAME/$DISTRO/$ARCH/$FILE" ] ; then 
+                    mv "$DIRNAME/$DISTRO/$ARCH/$FILE" "/$DISTRO/$ARCH/$FILE.$TIMESTAMP"
                 fi
             done
 
             echo "Creating tmp dir"
             TMP="$( mktemp -d )"
-            mkdir -p $TMP/initrd ; cd $TMP || die "Failed to create temp dir ./tmp/initrd"
+            mkdir -p $TMP/initrd ; cd $TMP || die "Failed to create temp dir $TMP/initrd"
 
             echo "Getting current initrd and kernel from ftp.nl.debian.org"
             wget -O "$TMP/initrd.gz" "$MIRROR/dists/$DISTRO/main/installer-$ARCH/current/images/netboot/debian-installer/$ARCH/initrd.gz" || die "Failed to download the new kernel"
@@ -61,14 +62,14 @@ function main() {
             cp -Rav $TMP/tmp/firmware-nonfree/bnx2/bnx2* $TMP/initrd/lib/firmware/
     
             echo "Copying kernel"
-            cp -v "$TMP/linux" "./$DISTRO/$ARCH"
+            cp -v "$TMP/linux" "$DIRNAME/$DISTRO/$ARCH/linux"
 
             echo "Building new initrd.gz"
-            pack "$TMP/initrd" "./$DISTRO/$ARCH"
+            pack "$TMP/initrd" "$DIRNAME/$DISTRO/$ARCH"
 
             echo "Removing tmp dir $TMP"
             rm -rf "$TMP"
-            echo "Done! copied to ./$DISTRO/$ARCH/initrd.gz"
+            echo "Done! copied to $DIRNAME/$DISTRO/$ARCH/initrd.gz"
         done
     done
 
