remove firmware in debian, add utopic to menu

diff --git a/tftp/distro/debian/setup b/tftp/distro/debian/setup
--- a/tftp/distro/debian/setup
+++ b/tftp/distro/debian/setup
@@ -18,57 +18,21 @@ function pack() { cd $1 ; find . | cpio --create --format='newc' | gzip -9  > "$
 function unpack() { cd $1; cat $2 | gzip -d | cpio --extract --preserve --verbose ; }
 
 function main() {
-    for DISTRO in squeeze wheezy
-    do 
+    for DISTRO in jessie wheezy squeeze; do
         echo "Preparing for $DISTRO"
-        for ARCH in "i386" "amd64"
-            do
-            echo "Setting up $ARCH"
+        for ARCH in "i386" "amd64"; do 
 
-            if [ ! -d "$DIRNAME/$DISTRO/$ARCH" ] ; then 
-                mkdir -p "$DIRNAME/$DISTRO/$ARCH" || die "Failed to create $DISTRO/$ARCH"
-            fi 
+            echo "Preparing for $DISTRO"
+            if [ ! -d "$DIRNAME/$DISTRO/$ARCH" ] ; then
+                mkdir -p "$DIRNAME/$DISTRO/$ARCH" || die "Failed to create $DIRNAME/$DISTRO/$ARCH"
+            fi
         
-            echo "Backing up current kernel and initrd.gz"
-            for FILE in linux initrd.gz
-            do
-               if [ -f "$DIRNAME/$DISTRO/$ARCH/$FILE" ] ; then 
-                    mv "$DIRNAME/$DISTRO/$ARCH/$FILE" "/$DISTRO/$ARCH/$FILE.$TIMESTAMP"
+            for FILE in linux initrd.gz ; do 
+                if [ -f "$DIRNAME/$DISTRO/$ARCH/$FILE" ] ; then
+                    mv "$DIRNAME/$DISTRO/$ARCH/$FILE" "$DIRNAME/$DISTRO/$ARCH/$FILE.$TIMESTAMP"
                 fi
+                wget -O "$DIRNAME/$DISTRO/$ARCH/$FILE"       "$MIRROR/dists/$DISTRO/main/installer-$ARCH/current/images/netboot/debian-installer/$ARCH/$FILE" || die "Failed to download $FILE for $DISTRO $ARCH"
             done
-
-            echo "Creating tmp dir"
-            TMP="$( mktemp -d )"
-            mkdir -p $TMP/initrd ; cd $TMP || die "Failed to create temp dir $TMP/initrd"
-
-            echo "Getting current initrd and kernel from ftp.nl.debian.org"
-            wget -O "$TMP/initrd.gz" "$MIRROR/dists/$DISTRO/main/installer-$ARCH/current/images/netboot/debian-installer/$ARCH/initrd.gz" || die "Failed to download the new kernel"
-            wget -O "$TMP/linux"     "$MIRROR/dists/$DISTRO/main/installer-$ARCH/current/images/netboot/debian-installer/$ARCH/linux"     || die "Failed to download the new kernel!"
-
-            echo "Unpacking initrd"
-            unpack "$TMP/initrd" "$TMP/initrd.gz"
-
-            echo "Getting the latest bnx2 firmware"
-            L="$( curl "$MIRROR/pool/non-free/f/firmware-nonfree/" 2>&1 | grep -E "firmware-nonfree.*$DISTRO.*\.tar\.gz" | awk -F "href=" '{print $2}' | awk -F '"' '{print $2}' )"
-            echo "LATEST IS $L"
-            wget -O "$TMP/firmware.tgz" "$MIRROR/pool/non-free/f/firmware-nonfree/$L" || die "Failed to get $LATEST latest firmware from ftp.nl.debian.org"
-
-            echo "Unpacking the bnx2 firmware in place"
-            mkdir "$TMP/tmp" ; cd "$TMP/tmp" || die "Does not compute mkdir fail"
-            tar xzf "$TMP/firmware.tgz"      || die "Failed to unpack firmware"
-
-            echo "Putting firmware in place"
-            mkdir -p "$TMP/initrd/lib/firmware/" || die "Failed to create $TMP/initrd/lib/firmware"
-            cp -Rav $TMP/tmp/firmware-nonfree/bnx2/bnx2* $TMP/initrd/lib/firmware/
-    
-            echo "Copying kernel"
-            cp -v "$TMP/linux" "$DIRNAME/$DISTRO/$ARCH/linux"
-
-            echo "Building new initrd.gz"
-            pack "$TMP/initrd" "$DIRNAME/$DISTRO/$ARCH"
-
-            echo "Removing tmp dir $TMP"
-            rm -rf "$TMP"
             echo "Done! copied to $DIRNAME/$DISTRO/$ARCH/initrd.gz"
         done
     done
